clc;
data1 = textread('1_linear.txt')/255;
data4 = textread('1_cubic.txt')/255;
data2 = textread('Newton_linear.txt')/255;
data3 = textread('Newton_cubic.txt')/255;
figure('NumberTitle', 'off', 'Name', '拉格朗日线性插值');
imshow(data1);
 figure('NumberTitle', 'off', 'Name', '拉格朗日三次插值');
imshow(data4);
figure('NumberTitle', 'off', 'Name', '牛顿线性插值');
imshow(data2);
 figure('NumberTitle', 'off', 'Name', '牛顿三次插值');
imshow(data3);
